### ISSUE TITLE
Where is find_links_tree defined?

### ISSUE THREAD

**Issue by taewookim** [fluquid/extract-social-media#4]

**Comment by codinguncut** [comment]
https://github.com/fluquid/extract-social-media/blob/20d6ff39f8778c0b6832065eed43d6013a6a2207/src/extract_social_media/__init__.py

**Comment by taewookim** [comment]
Oic.. sorry.. got lazy.

You forgot 

`from extract_social_media import find_links_tree
`

in  your example
