### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by bonchae** [fluquid/extract-social-media#6]
```
import requests
from html_to_etree import parse_html_bytes
from extract_social_media import find_links_tree

res = requests.get('http://www.costco.com')
tree = parse_html_bytes(res.content, res.headers.get('content-type'))

set(find_links_tree(tree))
```

The package seems not working for this particular website (costco).

**Comment by codinguncut** [comment]
I just had a look, and it could be that the code is not handling schema-less hyperlinks`<a href="//www.facebook.com/costco">` well at the moment.
I'll have a look at it.

**Comment by codinguncut** [comment]
Yes, the code currently assumes a prefix of `r'https?://`, so I will need to change that to also allow schema-less urls.

**Comment by bonchae** [comment]
That makes sense. Thanks.
